export const sex = [
  {id: 1, title: 'Gelding', status: false},
  {id: 2, title: 'Mare', status: false},
  {id: 3, title: 'Stallion', status: false}, 
];

export const breed = [
  {id: 1, title: 'American Quarter Horse', status: false},
  {id: 2, title: 'American Paint ', status: false},
  {id: 3, title: 'American Quarter Pony', status: false},
  {id: 4, title: 'American Saddlebred', status: false},
  {id: 5, title: 'American Warmblood', status: false},
  {id: 6, title: 'Andalusian', status: false},
  {id: 7, title: 'Anglo-Arabian', status: false},
  {id: 8, title: 'Appaloosa', status: false},
  {id: 9, title: 'Australian Draught', status: false},
  {id: 10, title: 'Arabian', status: false},
  {id: 11, title: 'Australian Stock Horse', status: false},
  {id: 12, title: 'Azteca', status: false},
  {id: 13, title: 'Belgian', status: false},
  {id: 14, title: 'Brumby', status: false},
  {id: 15, title: 'Canadian', status: false},
  {id: 16, title: 'Canadian Warmblood', status: false},
  {id: 17, title: 'Clydesdale', status: false},
  {id: 18, title: 'Connemara', status: false},
  {id: 19, title: 'Colorado Ranger', status: false},
  {id: 20, title: 'Curly', status: false},
  {id: 21, title: 'Donkey', status: false},
  {id: 22, title: 'Draft Cross', status: false},
  {id: 23, title: 'Dutch Warmblood', status: false},
  {id: 24, title: 'Florida Cracker', status: false},
  {id: 25, title: 'Friesian', status: false},
  {id: 26, title: 'Galiceno', status: false},
  {id: 27, title: 'Hackney', status: false},
  {id: 28, title: 'Haflinger', status: false},
  {id: 29, title: 'Hanoverian', status: false},
  {id: 30, title: 'Holsteiner', status: false},
  {id: 31, title: 'Icelandic', status: false},
  {id: 32, title: 'Irish Sport Horse', status: false},
  {id: 33, title: 'Kentucky Mountain Saddle Horse', status: false},
  {id: 34, title: 'Lipizzan', status: false},
  {id: 35, title: 'Lusitano', status: false},
  {id: 36, title: 'Miniature Pony', status: false},
  {id: 37, title: 'Missouri Fox Trotter', status: false},
  {id: 38, title: 'Morgan', status: false},
  {id: 39, title: 'Mountain Pleasure', status: false},
  {id: 40, title: 'Mule', status: false},
  {id: 41, title: 'Mustang', status: false},
  {id: 42, title: 'Newfoundland Pony', status: false},
  {id: 43, title: 'Oldenburg', status: false},
  {id: 44, title: 'Percheron', status: false},
  {id: 45, title: 'Pony of the Americas', status: false},
  {id: 46, title: 'Racking', status: false},
  {id: 47, title: 'Rocky Mountain', status: false},
  {id: 48, title: 'Sable Island', status: false},
  {id: 49, title: 'Saddlebred', status: false},
  {id: 50, title: 'Selle Francais', status: false},
  {id: 51, title: 'Shetland Pony', status: false},
  {id: 52, title: 'Shire', status: false},
  {id: 53, title: 'Spotted Saddle', status: false},
  {id: 54, title: 'Standardbred', status: false},
  {id: 55, title: 'Tennessee Walking Horse', status: false},
  {id: 56, title: 'Thoroughbred', status: false},
  {id: 57, title: 'Tiger Horse', status: false},
  {id: 58, title: 'Trakehner', status: false},
  {id: 59, title: 'Welsh Pony', status: false},
  {id: 60, title: 'Westphalian', status: false},
  {id: 61, title: 'Other', status: false},
];

export const height = [
  {id: 1, title: '<12 hands', status: false},
  {id: 2, title: '12.1 hands', status: false},
  {id: 3, title: '12.2 hands', status: false},
  {id: 4, title: '12.3 hands', status: false},
  {id: 5, title: '13 hands', status: false},
  {id: 6, title: '13.1 hands', status: false},
  {id: 7, title: '13.2 hands', status: false},
  {id: 8, title: '13.3 hands', status: false},
  {id: 9, title: '14 hands', status: false},
  {id: 10, title: '14.1 hands', status: false},
  {id: 11, title: '14.2 hands', status: false},
  {id: 12, title: '14.3 hands', status: false},
  {id: 13, title: '15 hands', status: false},
  {id: 14, title: '15.1 hands', status: false},
  {id: 15, title: '15.2 hands', status: false},
  {id: 16, title: '15.3 hands', status: false},
  {id: 17, title: '16 hands', status: false},
  {id: 18, title: '16.1 hands', status: false},
  {id: 19, title: '16.2 hands', status: false},
  {id: 20, title: '16.3 hands', status: false},
  {id: 21, title: '17 hands', status: false},
  {id: 22, title: '17.1 hands', status: false},
  {id: 23, title: '17.2 hands', status: false},
  {id: 24, title: '17.3 hands', status: false},
  {id: 25, title: '18 hands', status: false},
  {id: 26, title: '>18 hands', status: false},
];

export const weight = [
  {id: 1, title: '<300 pounds', status: false},
  {id: 2, title: '300-400 pounds', status: false},
  {id: 3, title: '401-500 pounds', status: false},
  {id: 4, title: '501-600 pounds', status: false},
  {id: 5, title: '601-700 pounds', status: false},
  {id: 6, title: '701-800 pounds', status: false},
  {id: 7, title: '801-900 pounds', status: false},
  {id: 8, title: '901-1000 pounds', status: false},
  {id: 9, title: '1001-1100 pounds', status: false},
  {id: 10, title: '1101-1200 pounds', status: false},
  {id: 11, title: '1201-1300 pounds', status: false},
  {id: 12, title: '1301-1400 pounds', status: false},
  {id: 13, title: '1401-1500 pounds', status: false},
  {id: 14, title: '1501-1600 pounds', status: false},
  {id: 15, title: '1601-1700 pounds', status: false},
  {id: 16, title: '1701-1800 pounds', status: false},
  {id: 17, title: '1801-1900 pounds', status: false},
  {id: 18, title: '1901-2000 pounds', status: false},
  {id: 19, title: '>2000 pounds', status: false},
];

export const color = [
  {id: 1, title: 'Amber Champagne', status: false},
  {id: 2, title: 'Bay', status: false},
  {id: 3, title: 'Bay Roan', status: false},
  {id: 4, title: 'Black', status: false},
  {id: 5, title: 'Blood Bay', status: false},
  {id: 6, title: 'Blue Roan', status: false},
  {id: 7, title: 'Brindle', status: false},
  {id: 8, title: 'Brown', status: false},
  {id: 9, title: 'Brown Roan', status: false},
  {id: 10, title: 'Buckskin', status: false},
  {id: 11, title: 'Classic Champagne', status: false},
  {id: 12, title: 'Chestnut', status: false},
  {id: 13, title: 'Cream', status: false},
  {id: 14, title: 'Cremello', status: false},
  {id: 15, title: 'Dapple Gray', status: false},
  {id: 16, title: 'Dark Bay', status: false},
  {id: 17, title: 'Dun', status: false},
  {id: 18, title: 'Flaxen Chestnut', status: false},
  {id: 19, title: 'Gold Champagne', status: false},
  {id: 20, title: 'Gray', status: false},
  {id: 21, title: 'Grullo', status: false},
  {id: 22, title: 'Leopard', status: false},
  {id: 23, title: 'Liver Chestnut', status: false},
  {id: 24, title: 'Overo', status: false},
  {id: 25, title: 'Palomino', status: false},
  {id: 26, title: 'Pearl', status: false},
  {id: 27, title: 'Perlino', status: false},
  {id: 28, title: 'Piebald', status: false},
  {id: 29, title: 'Pinto', status: false},
  {id: 30, title: 'Rabicano', status: false},
  {id: 31, title: 'Red Dun', status: false},
  {id: 32, title: 'Red Roan', status: false},
  {id: 33, title: 'Rose Gray', status: false},
  {id: 34, title: 'Silver Dapple', status: false},
  {id: 35, title: 'Skewbald', status: false},
  {id: 36, title: 'Smoky Black', status: false},
  {id: 37, title: 'Smoky Cream', status: false},
  {id: 38, title: 'Snowflake', status: false},
  {id: 39, title: 'Sorrel', status: false},
  {id: 40, title: 'Tobiano', status: false},
  {id: 41, title: 'Tovero', status: false},
  {id: 42, title: 'Varnish Roan', status: false},
  {id: 43, title: 'White', status: false},
];

export const price = [
  {id: 1, title: 'None', status: false},
  {id: 2, title: '$0.00 - $1,000.00', status: false},
  {id: 3, title: '$1,000.00 - $5,000.00', status: false},
  {id: 4, title: '$5,000.00 - $10,000.00', status: false},
  {id: 5, title: '$10,000.00 - $20,000.00', status: false},
  {id: 6, title: '$20.000.00 - $30,000.00', status: false},
  {id: 7, title: '$30,000.00 - $50,000.00', status: false},
  {id: 8, title: '$50,000.00 - $100,000.00', status: false},
  {id: 9, title: '$100,000.00 - $150,000.00', status: false},
  {id: 9, title: '$150,000.00 - $200,000.00', status: false},

  {id: 10, title: '$200,000.00 - $300,000.00', status: false},
  {id: 11, title: '$300,000.00 - $500,000.00', status: false},
  {id: 12, title: '$500,000.00 - $1,000,000.00', status: false},
  {id: 13, title: '>$1,000,000.00', status: false},
];
export const training = [
  {id: 1, title: 'None', status: false},
  {id: 2, title: 'Basic Handling', status: false},
  {id: 3, title: 'Basic Gentling and Handling', status: false},
  {id: 4, title: 'Halter and Lead Broke', status: false},
  {
    id: 5,
    title: 'Leads, Loads in Trailer, Stands Tied for Farrier Work ',
    status: false,
  },
  {
    id: 6,
    title: 'Leads, Loads in Trailer, Stands Tied for Farrier Work, Bathes',
    status: false,
  },
  {
    id: 7,
    title:
      'Leads, Loads in Trailer, Stands Tied for Farrier Work, Bathes, Clips',
    status: false,
  },
  {
    id: 8,
    title:
      'Leads, Loads in Trailer, Stands Tied for Farrier Work, Bathes, Clips, Hobbles',
    status: false,
  },
  {id: 9, title: '0-30 Days Riding Training', status: false},
  {id: 10, title: '30-60 Days Riding Training', status: false},
  {id: 11, title: '60-90 Days Riding Training', status: false},
  {id: 12, title: '90-120 Days Riding Training', status: false},
  {id: 13, title: '4-6 Months Riding Training', status: false},
  {id: 14, title: '6-12 Months Riding Training', status: false},
  {id: 15, title: '12 Months Riding Training', status: false},
  {id: 16, title: '24 Months Riding Training', status: false},
  {id: 17, title: '36 Months Riding Training', status: false},
  {
    id: 18,
    title: 'Finished Riding Training - Not Currently Shown',
    status: false,
  },
  {id: 19, title: 'Finished Riding Training - Currently Shown', status: false},
  {
    id: 20,
    title: 'Finished Riding Training - Currently in Shown and Training',
    status: false,
  },
  {id: 21, title: 'Trained and Currently Riding', status: false},
  {id: 22, title: 'Trained and Currently Used for Work', status: false},
];

export const discipline = [
  {id: 1, title: 'Acting', status: false},
  {id: 2, title: 'All Around Rodeo', status: false},
  {id: 3, title: 'Barrel Racing', status: false},
  {id: 4, title: 'Breakaway Roping', status: false},
  {id: 5, title: 'Bucking Stock', status: false},
  {id: 6, title: 'Calf Roping', status: false},
  {id: 7, title: 'Campdrafting', status: false},
  {id: 8, title: 'Cutting', status: false},
  {id: 9, title: 'Cross Country', status: false},
  {id: 10, title: 'Draft', status: false},
  {id: 11, title: 'Dressage', status: false},
  {id: 12, title: 'Equitation', status: false},
  {id: 13, title: 'English Pleasure', status: false},
  {id: 14, title: 'Eventing', status: false},
  {id: 15, title: 'Goat Tying', status: false},
  {id: 16, title: 'Halter', status: false},
  {id: 17, title: 'Hunter Jumper', status: false},
  {id: 18, title: 'Hunting', status: false},
  {id: 19, title: 'Jousting', status: false},
  {id: 20, title: 'Kid/Family', status: false},
  {id: 21, title: 'Leadline', status: false},
  {id: 22, title: 'Packing', status: false},
  {id: 23, title: 'Para-equestrian Dressage', status: false},
  {id: 24, title: 'Playday Events', status: false},
  {id: 25, title: 'Pole Bending', status: false},
  {id: 26, title: 'Police/Patrol', status: false},
  {id: 27, title: 'Pony', status: false},
  {id: 28, title: 'Ponying', status: false},
  {id: 29, title: 'Pulling', status: false},
  {id: 30, title: 'Racing', status: false},
  {id: 31, title: 'Ranch Pleasure', status: false},
  {id: 32, title: 'Ranch Reining', status: false},
  {id: 33, title: 'Ranch Rodeo', status: false},
  {id: 34, title: 'Ranch Trail', status: false},
  {id: 35, title: 'Ranching', status: false},
  {id: 36, title: 'Reined Cowhorse', status: false},
  {id: 37, title: 'Reining', status: false},
  {id: 38, title: 'Saddle Seat', status: false},
  {id: 39, title: 'Show Jumping', status: false},
  {id: 40, title: 'Steer Wrestling', status: false},
  {id: 41, title: 'Stock Horse', status: false},
  {id: 42, title: 'Team Penning', status: false},
  {id: 43, title: 'Team Ranch Sorting', status: false},
  {id: 44, title: 'Team Roping', status: false},
  {id: 45, title: 'Therapy', status: false},
  {id: 46, title: 'Trail', status: false},
  {id: 47, title: 'Western Dressage', status: false},
  {id: 48, title: 'Western Pleasure', status: false},
  {id: 49, title: 'Other', status: false},
];

export const condition = [
  {
    id: 1,
    title: 'Performance Shape - Healthy and Sound to Show without Maintenance',
    status: false,
  },
  {
    id: 2,
    title: 'Performance Shape - Healthy and Sound to Show with Maintenance',
    status: false,
  },
  {
    id: 3,
    title: 'Healthy - Legged Up with No Major Medical Issues',
    status: false,
  },
  {
    id: 4,
    title: 'Healthy - Needs Leggged Up with No Major Medical Issues',
    status: false,
  },
  {
    id: 5,
    title: 'Healthy - Does Not Require Any Special Medical Care',
    status: false,
  },
  {id: 6, title: 'Healthy - Requires Special Medical Care', status: false},
  {id: 7, title: 'Healthy - Not Sound to Ride', status: false},
  {id: 8, title: 'Healthy - Broodmare Sound Only', status: false},
  {id: 9, title: 'Healthy - Underweight ', status: false},
  {id: 10, title: 'Healthy - Aging Condition', status: false},
  {id: 11, title: 'Unhealthy - Known Health Issues', status: false},
  {id: 12, title: 'Unhealthy - Unkown Health Issues', status: false},
];
