export const arrName = [
    {component: ProfileScreen, name: 'ProfileScreen'},
    {component: SignIn, name: 'SignIn'},
    {component: HorseRegister, name: 'HorseRegister'},
    {component: MyHorses, name: 'MyHorses'},
    {component: ChangeHorseInfo, name: 'ChangeHorseInfo'},
    {component: EditProfile, name: 'EditProfile'},
    {component: ChangePassword, name: 'ChangePassword'},
    {component: AccountInfo, name: 'AccountInfo'},
    {component: AddNewCard, name: 'AddNewCard'},
    {component: ViewAllTransactions, name: 'ViewAllTransactions'},
    {component: TransactionFilter, name: 'TransactionFilter'},
    {component: MyFavorites, name: 'MyFavorites'},
    {component: HorseInfo, name: 'HorseInfo'},
    {component: OwnerProfile, name: 'OwnerProfile'},
    {component: PaymentMethod, name: 'PaymentMethod'},
    {component: HorseRegComplite, name: 'HorseRegComplite'},
    {component: Privacy, name: 'Privacy'},
    {component: SignUp, name: 'SignUp'},
    {component: ForgotByEmail, name: 'ForgotByEmail'},
    {component: MyBoughtenHorses, name: 'MyBoughtenHorses'},
    {component: MyContracts, name: 'MyContracts'},
    {component: NewContract, name: 'NewContract'},
  ];